"""AI disclosure — generate transparent, configurable disclosure statements.

AIDisclosure produces user-facing statements that inform end users they are
interacting with an AI system. Statements are generated from named templates
and can be customised with a tone setting and deployment-specific configuration.

Template categories
-------------------
- initial_greeting     : Shown at the start of a conversation.
- response_caveat      : Appended to individual responses where warranted.
- handoff_notice       : Shown when handing off to a human agent.
- data_usage_notice    : Explains how conversation data may be used.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from string import Template


class DisclosureTone(str, Enum):
    """Tone setting that affects the register and formality of disclosures."""

    FORMAL = "formal"
    FRIENDLY = "friendly"
    CONCISE = "concise"


# ---------------------------------------------------------------------------
# Template library
# ---------------------------------------------------------------------------

# Each template is a string.Template with $-style substitution variables.
# Variables available in all templates:
#   $agent_name  - Display name of the AI agent (default: "AI Assistant")
#   $org_name    - Name of the deploying organisation (default: "")

_TEMPLATES: dict[str, dict[DisclosureTone, str]] = {
    "initial_greeting": {
        DisclosureTone.FORMAL: (
            "You are now communicating with $agent_name, an artificial intelligence "
            "system operated by $org_name. Please be aware that responses are generated "
            "automatically and may not reflect expert professional advice."
        ),
        DisclosureTone.FRIENDLY: (
            "Hi there! I am $agent_name, an AI assistant from $org_name. "
            "I am here to help — and I will always let you know if a question "
            "is best answered by a human expert."
        ),
        DisclosureTone.CONCISE: (
            "AI: $agent_name ($org_name). Responses are automated."
        ),
    },
    "response_caveat": {
        DisclosureTone.FORMAL: (
            "This response was generated by $agent_name, an AI system. "
            "It may contain errors or omissions. Please verify critical information "
            "with a qualified professional."
        ),
        DisclosureTone.FRIENDLY: (
            "Just a heads-up: I am an AI ($agent_name) and I can sometimes get "
            "things wrong. If this is important, it is worth double-checking with "
            "a human expert."
        ),
        DisclosureTone.CONCISE: (
            "[AI-generated — verify independently]"
        ),
    },
    "handoff_notice": {
        DisclosureTone.FORMAL: (
            "Your conversation is being transferred to a human representative of "
            "$org_name. The context of your interaction with $agent_name has been "
            "shared with your assigned agent to ensure continuity."
        ),
        DisclosureTone.FRIENDLY: (
            "I am connecting you with a real person from $org_name who can help "
            "further. I have shared a summary of our conversation so you will not "
            "need to repeat yourself."
        ),
        DisclosureTone.CONCISE: (
            "Transferring to human agent ($org_name). Context shared."
        ),
    },
    "data_usage_notice": {
        DisclosureTone.FORMAL: (
            "Interactions with $agent_name may be logged and reviewed by $org_name "
            "for quality assurance, safety monitoring, and service improvement "
            "purposes, in accordance with our privacy policy."
        ),
        DisclosureTone.FRIENDLY: (
            "To keep improving, $org_name may review conversations with $agent_name. "
            "Your privacy matters to us — see our privacy policy for details."
        ),
        DisclosureTone.CONCISE: (
            "Conversations logged by $org_name per privacy policy."
        ),
    },
}

_VALID_TEMPLATES: frozenset[str] = frozenset(_TEMPLATES.keys())


@dataclass(frozen=True)
class DisclosureStatement:
    """A rendered disclosure statement.

    Attributes
    ----------
    template_name:
        The name of the template that produced this statement.
    tone:
        The tone applied when rendering.
    text:
        The rendered disclosure text ready for display.
    """

    template_name: str
    tone: DisclosureTone
    text: str


class AIDisclosure:
    """Generate AI transparency and disclosure statements.

    Parameters
    ----------
    agent_name:
        Display name for the AI agent (inserted into templates).
    org_name:
        Name of the deploying organisation.
    tone:
        Tone for rendered statements. Defaults to FRIENDLY.
    custom_templates:
        Optional mapping of template_name -> DisclosureTone -> text that
        overrides or extends the built-in library.

    Example
    -------
    >>> disclosure = AIDisclosure(agent_name="Aria", org_name="Acme Corp")
    >>> stmt = disclosure.generate("initial_greeting")
    >>> "Aria" in stmt.text
    True
    """

    def __init__(
        self,
        agent_name: str = "AI Assistant",
        org_name: str = "",
        tone: DisclosureTone = DisclosureTone.FRIENDLY,
        custom_templates: dict[str, dict[DisclosureTone, str]] | None = None,
    ) -> None:
        self._agent_name = agent_name
        self._org_name = org_name
        self._tone = tone
        self._templates: dict[str, dict[DisclosureTone, str]] = dict(_TEMPLATES)
        if custom_templates:
            for name, tone_map in custom_templates.items():
                if name in self._templates:
                    self._templates[name] = {**self._templates[name], **tone_map}
                else:
                    self._templates[name] = tone_map

    # ------------------------------------------------------------------
    # Core generation
    # ------------------------------------------------------------------

    def generate(
        self,
        template_name: str,
        tone: DisclosureTone | None = None,
        extra_vars: dict[str, str] | None = None,
    ) -> DisclosureStatement:
        """Render a named disclosure template.

        Parameters
        ----------
        template_name:
            One of: ``initial_greeting``, ``response_caveat``,
            ``handoff_notice``, ``data_usage_notice``, or any custom name
            registered at construction time.
        tone:
            Override the instance-level tone for this render only.
        extra_vars:
            Additional substitution variables to inject into the template.

        Returns
        -------
        DisclosureStatement
            Frozen rendered statement.

        Raises
        ------
        ValueError
            If ``template_name`` is not registered.
        """
        if template_name not in self._templates:
            available = sorted(self._templates.keys())
            raise ValueError(
                f"Unknown disclosure template {template_name!r}. "
                f"Available templates: {available!r}."
            )
        resolved_tone = tone if tone is not None else self._tone
        tone_map = self._templates[template_name]

        # Fall back to FRIENDLY then CONCISE if the exact tone is missing.
        raw_template = (
            tone_map.get(resolved_tone)
            or tone_map.get(DisclosureTone.FRIENDLY)
            or next(iter(tone_map.values()))
        )

        variables: dict[str, str] = {
            "agent_name": self._agent_name,
            "org_name": self._org_name or "your organisation",
        }
        if extra_vars:
            variables.update(extra_vars)

        rendered = Template(raw_template).safe_substitute(variables)
        return DisclosureStatement(
            template_name=template_name,
            tone=resolved_tone,
            text=rendered,
        )

    def generate_all(
        self, tone: DisclosureTone | None = None
    ) -> dict[str, DisclosureStatement]:
        """Render all registered templates.

        Parameters
        ----------
        tone:
            Override the instance-level tone for all renders.

        Returns
        -------
        dict[str, DisclosureStatement]
            Maps template name to its rendered statement.
        """
        return {
            name: self.generate(name, tone=tone)
            for name in sorted(self._templates.keys())
        }

    def available_templates(self) -> list[str]:
        """Return a sorted list of available template names."""
        return sorted(self._templates.keys())

    def set_tone(self, tone: DisclosureTone) -> None:
        """Update the default rendering tone.

        Parameters
        ----------
        tone:
            The new default DisclosureTone.
        """
        self._tone = tone
